# 03 numpy.array基础

### 加载numpy和查看版本

In [ ]:
import numpy

In [2]:
numpy.__version__

'1.21.5'

In [3]:
import numpy as np

In [4]:
np.__version__

'1.21.5'

### Python List的特点
* 灵活但效率低

In [7]:
L = [i for i in range(10)]
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
L[5] = 100
L

[0, 1, 2, 3, 4, 100, 6, 7, 8, 9]

In [11]:
L[6] = "Machine learning"
L

[0, 1, 2, 3, 4, 100, 'Machine learning', 7, 8, 9]

### array
* 降低了灵活性，效率比较高
* array只是视为数组，没有提供向量或矩阵的相应计算

In [12]:
import array

In [19]:
arr = array.array('i', [i for i in range(10)])
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[5] = 100

### numpy.array
* 和python的array类似
* 封装了一些方法

In [17]:
nparr = np.array([i for i in range(10)])
nparr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
nparr.dtype

dtype('int32')

In [29]:
nparr[5] = 3.2
nparr

array([0, 1, 2, 3, 4, 3, 6, 7, 8, 9])

In [30]:
nparr.dtype

dtype('int32')

In [31]:
nparr = np.array([1, 2, 3.12])

In [32]:
nparr.dtype

dtype('float64')

### 其他创建 numpy.array的方法

In [33]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
np.zeros(10).dtype

dtype('float64')

In [35]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.zeros(shape=(3,5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [38]:
np.ones((3,5)) #3行5列的矩阵

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [43]:
np.full((3,5),fill_value=666)

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

In [44]:
np.full((3,5),fill_value=666).dtype

dtype('int32')

In [46]:
np.full((3,5),fill_value=666.0).dtype

dtype('float64')

In [47]:
np.full(fill_value=666, shape=(3,5)) #参数顺序可以交换，传两个参数最好注明参数名称，方便阅读

array([[666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666],
       [666, 666, 666, 666, 666]])

### arrange

In [48]:
[i for i in range(0, 20, 2)]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [50]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])